/**
 * Twin Visit Logger — Daily Opportunity Report.
 * Builds a business-day report of actionable records and either emails it to
 * CFG.REPORT_TO (internal staff only) or writes it to a "Daily Report" sheet.
 * Never messages a seller.
 */

function sendDailyReport() {
  const d = new Date();
  const g = d.getDay();
  // Business days only for the scheduled trigger; manual/preview runs still build the sheet.
  const sections = reportSections_();
  const total = sections.reduce(function(n,s){ return n + s.rows.length; }, 0);
  const sendEmpty = false;

  writeReportSheet_(sections, total);           // always refresh the Daily Report sheet
  let emailed = false;
  if (CFG.REPORT_TO && !(total === 0 && !sendEmpty)) {
    const html = renderReportHtml_(sections, total);
    MailApp.sendEmail({ to: CFG.REPORT_TO, subject: CFG.REPORT_TITLE + ' — ' + fmt_(today_()), htmlBody: html });
    emailed = true;
  }
  logAuto_('REPORT', '', 'Daily report built (' + total + ' actionable). Emailed=' + emailed + (CFG.REPORT_TO ? '' : ' (REPORT_TO blank — no email)'));
  return { emailed: emailed, total: total, recipient: CFG.REPORT_TO || '(none)' };
}

/** The 10 report sections, computed from Data (same logic as the Board). */
function reportSections_() {
  const rows = readAllRows_();
  // live report excludes Source=TEST demo records
  const active = rows.filter(function(r){ return r['Property Address'] && r['Source'] !== 'TEST'; });
  function f(pred){ return active.filter(pred); }
  const ov = function(r){ return Number(r['Days Overdue']) || 0; };

  return [
    { title: 'Contracts Possible This Week',
      rows: f(function(r){ return ['Verbal Agreement','Contract Sent','Active Negotiation'].indexOf(r['Current Stage'])>=0; })
              .sort(function(a,b){ return (Number(b['Opportunity Priority'])||0)-(Number(a['Opportunity Priority'])||0); }) },
    { title: 'Visited — No Offer Decision',
      rows: f(function(r){ return r['Current Stage']==='Visit Completed — Needs Review'; }).sort(byOverdue_) },
    { title: 'Offer Sent — Follow-Up Due',
      rows: f(function(r){ return r['Current Stage']==='Offer Sent'; }).sort(byOverdue_) },
    { title: 'Stalled Deals',
      rows: f(function(r){ return r['Stalled Status']==='Yes'; }).sort(byOverdue_) },
    { title: 'Overdue Tasks',
      rows: f(function(r){ return ov(r)>0; }).sort(byOverdue_) },
    { title: 'Negotiation Decisions',
      rows: f(function(r){ return r['Current Stage']==='Active Negotiation'; }) },
    { title: 'Contract Handoffs',
      rows: f(function(r){ return r['Current Stage']==='Contract Signed' && r['Transaction Handoff Status']!=='Handoff Confirmed'; }) },
    { title: 'Gift Review',
      rows: f(function(r){ return r['Gift Status']==='Recommended'; }) },
    { title: 'Revival Opportunities',
      rows: f(function(r){ return r['Final Disposition']==='Lost' && (Number(r['Days Since Last Activity'])||0)>=45; }) },
    { title: 'Exceptions',
      rows: f(function(r){ return r['Data Quality Status']==='Exception' || r['Data Quality Status']==='Incomplete'; }) },
  ];
}
function byOverdue_(a,b){ return (Number(b['Days Overdue'])||0)-(Number(a['Days Overdue'])||0); }

function renderReportHtml_(sections, total) {
  const cols = ['Property Address','Seller Name','Current Stage','Next Action','Assigned Owner','Next Action Due Date','Days Overdue','Blocker'];
  let h = '<div style="font-family:Arial,sans-serif;font-size:13px;color:#222">';
  h += '<h2 style="color:#1f4e79;margin:0 0 4px">' + CFG.REPORT_TITLE + '</h2>';
  h += '<div style="color:#666">' + fmt_(today_()) + ' · ' + total + ' actionable records</div>';
  sections.forEach(function(s){
    h += '<h3 style="background:#2e75b6;color:#fff;padding:6px 8px;margin:14px 0 0;border-radius:4px">' +
         s.title + ' (' + s.rows.length + ')</h3>';
    if (!s.rows.length) { h += '<div style="color:#999;padding:6px">— none —</div>'; return; }
    h += '<table style="border-collapse:collapse;width:100%;margin-top:4px"><tr>';
    cols.forEach(function(c){ h += '<th style="text-align:left;border-bottom:2px solid #ccc;padding:4px;font-size:11px">' + c + '</th>'; });
    h += '</tr>';
    s.rows.forEach(function(r){
      const overdue = (Number(r['Days Overdue'])||0) > 0;
      h += '<tr style="background:' + (overdue ? '#fdECEC' : '#fff') + '">';
      cols.forEach(function(c){
        let v = r[c]; if (c.indexOf('Date')>=0 && v) v = fmt_(v);
        h += '<td style="border-bottom:1px solid #eee;padding:4px;font-size:12px">' + (v==null?'':v) + '</td>';
      });
      h += '</tr>';
    });
    h += '</table>';
  });
  h += '<p style="color:#999;font-size:11px;margin-top:16px">Generated by Twin Visit Logger. Internal use only — no seller was contacted.</p></div>';
  return h;
}

function writeReportSheet_(sections, total) {
  const ss = SpreadsheetApp.getActive();
  let sh = ss.getSheetByName('Daily Report');
  if (!sh) sh = ss.insertSheet('Daily Report');
  sh.clear();
  sh.getRange(1,1).setValue(CFG.REPORT_TITLE + ' — ' + fmt_(today_()) + ' (' + total + ' actionable)')
    .setFontWeight('bold').setFontSize(13).setFontColor('#1f4e79');
  const cols = ['Property Address','Seller Name','Current Stage','Next Action','Assigned Owner','Next Action Due Date','Days Overdue','Blocker'];
  let row = 3;
  sections.forEach(function(s){
    sh.getRange(row,1,1,cols.length).merge();
    sh.getRange(row,1).setValue(s.title + ' (' + s.rows.length + ')').setFontWeight('bold').setFontColor('#fff').setBackground('#2e75b6');
    row++;
    sh.getRange(row,1,1,cols.length).setValues([cols]).setFontWeight('bold').setBackground('#ddebf7');
    row++;
    if (!s.rows.length) { sh.getRange(row,1).setValue('— none —').setFontColor('#999'); row+=2; return; }
    const data = s.rows.map(function(r){ return cols.map(function(c){ let v=r[c]; if(c.indexOf('Date')>=0&&v) v=fmt_(v); return v==null?'':v; }); });
    sh.getRange(row,1,data.length,cols.length).setValues(data);
    row += data.length + 1;
  });
}

function readAllRows_() {
  const sh = dataSheet_();
  const last = sh.getLastRow();
  if (last < CFG.FIRST_DATA_ROW) return [];
  const vals = sh.getRange(CFG.FIRST_DATA_ROW, 1, last - CFG.FIRST_DATA_ROW + 1, HEADERS.length).getValues();
  return vals.map(function(v){ const o={}; HEADERS.forEach(function(h,i){ o[h]=v[i]; }); return o; });
}
